site_name: 浙江大学2025-2026学年秋冬学期微积分（甲）I辅学
site_url: https://zjucalc25.github.io/
site_author: yuanhongyi2004

extra:
  social:
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/3546574332365752
    - icon: fontawesome/brands/github
      link: https://github.com/yuanhongyi/zjucalc24


theme: 
  name: material #主题
  logo: graph/ZJU-logo.svg
  favicon: graph/ZJU-logo.svg 
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    repo: fontawesome/brands/github
    edit: material/pencil
  features:
    - search.highlight
#    - navigation.instant
    - navigation.expand
    - navigation.footer
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
#    - navigation.prune
    - navigation.indexes
    - navigation.top
    - header.autohide
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.tabs.link
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    code: JetBrains Mono
    text: Noto Serif SC


markdown_extensions:
  - admonition
  # Python Markdown
  - toc:
      permalink: true
      toc_depth: 3
  - abbr
  - def_list
  - attr_list
  - footnotes
  - md_in_html
  - admonition
  - sane_lists
  # Python Markdown Extensions
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - neoteroi.cards # install using `pip install neoteroi-mkdocs`

extra_javascript:
  - https://jsd.onmicrosoft.cn/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
extra_css:
  - stylesheets/neoteroi-mkdocs.css
  - stylesheets/custom.css

plugins:
  - search
  - glightbox # install using `pip install mkdocs-glightbox`
  - heti:
      extra_skipped_class:
        - arithmatex
      disable_serve: false
  - git-revision-date-localized
  - mkdocs-pdf
  # x- table-reader
  # - git-authors
  # - git-committers
  # x- with-pdf


nav:
  - Preface: 
    - Preface: index.md
  - Slides:
    - 数列与函数:
      - 数列极限: slides/seq.md
      - 函数: slides/func.md
    - 微分中值定理:
      - 定理证明、构造函数、双中值问题(期中): slides/diff_mean.md
      - 罗尔定理、导数介值定理: slides/rolle.md
      - 辅助多项式: slides/poly.md
      - 泰勒公式: slides/taylor.md
      - K值法: slides/constK.md
    - 泰勒公式与洛必达法则:
      - 极限计算: slides/limit.md
    - 不定积分:
      - 积分表: slides/int/int_table.md
      - 有理函数积分: slides/int/indef/rational.md
      - 三角有理函数积分: slides/int/indef/tri_rational.md
      - 换元法与分部积分法: slides/int/indef/substitution_integration.md
    - 定积分:
      - 定积分基础: slides/int/def/1.md
      - 定积分拓展: slides/int/def/2.md
      - 区间再现公式: slides/int/def/3.md
    - 积分不等式:
      - 方法汇总: slides/int_ineq/all.md
      - 构造变限积分: slides/int_ineq/1.md
      - 利用中值定理: slides/int_ineq/2.md
    - 反常积分:
      - 反常积分敛散性: slides/int/improper/1.md
      - 反常积分计算: slides/int/improper/2.md

  - Quiz:
    - 24微甲小测1: quiz/calc_quiz1.md
    - 24微甲小测2: quiz/calc_quiz2_1.md
    - 24数分H小测2: quiz/anal_quiz2.md
  - Exam:
    - 期中:
      - 期考: exam/index.md
      - 25期中样卷: exam/mid/sim.md
      - 期中分类整理: exam/mid/categoried.md
      - 期中模拟试题解析: exam/mid/test_with_ans.md
      - 期中模拟试题: exam/mid/test.md
    - 期末:
      - 期末考情分析: exam/final/final_exam_analysis.md
      - 25期末模拟: exam/final/25final_sim.md
      # - 模拟题分析与解答: exam/final/report&ans.md
      - 24期末部分分析: exam/final/24final.md
  - PDF: 
    - index: pdf/index.md
    - 22、23微积分(H/甲)I第一次小测: pdf/quiz1/1.md
  - Misc:
    - Index: misc/index.md
    - 23H.8定积分对称性: misc/20241205.md
    - 习题6.51两种解法: misc/20241209.md
    - 23J.15积分不等式: misc/20241210.md
    - 21J.12积分不等式: misc/20241211.md
    - 敛迫性+定积分定义: misc/20241212.md
    - 18J.13Young不等式: misc/20241213.md
    - 22H.15Dunkel不等式: misc/20241214.md
    - 22H.16微分中值定理: misc/20241215.md
    - 18H.12凸函数连续性: misc/20241216.md
    - 具体函数的中值极限: misc/20241217.md
    - 积分的极限1: misc/20241218.md
    - 20J.4积分的极限2: misc/20241219.md
    - 20J.11下凸函数Lip连续: misc/20241220.md
    - 20J.9周期积分平均: misc/20241221.md
    - 20J.12Taylor/辅助多项式: misc/20241222.md
    - 16CMCT7仿照泰勒展开分析: misc/20241223.md
    - 25考研非数: misc/20241224.md
    - 泰勒展开证明强条件下琴生不等式: misc/20241227.md
    - 变限积分被积函数不连续: misc/20241228.md